### ISSUE TITLE
Make it responsive on mobile

### ISSUE THREAD

**Issue by egtann** [DaleWebb/abot-widget#2]
At the same time we can probably eliminate a bunch of things from the code like user-agent detection (which should be avoided where possible), and make it responsive on mobile purely by screen size / simple media queries in CSS.

**Comment by DaleWebb** [comment]
The widget responds just like Intercom's does via CSS (takes full-screen on mobile).  I haven't used the utility methods that refer to the user agent or device, but I have removed them now so that it indicates that they aren't to be used.

**Comment by egtann** [comment]
Interesting. I was testing it on "mobile phone simulator" mode in Chrome and it just shrunk  the screen in place (i.e. the sidebar was just really tiny). I'll keep testing

**Comment by DaleWebb** [comment]
Is that on the http://dalewebb.github.io/abot-widget page?  As I had forgotten to add this: `<meta name="viewport" content="initial-scale=1, maximum-scale=1">` to the demo page before.

**Comment by egtann** [comment]
Yup.  All good now!  Works perfectly.
