### ISSUE TITLE
HTTPS is broken

### ISSUE THREAD

**Issue by egtann** [DaleWebb/abot-widget#3]
widget.js is served via HTTP, which isn't allowed on HTTPS requests (mixed-request).

**Comment by DaleWebb** [comment]
I'm wondering if a web server is needed at all, as it only needs to serve the javascript file?

**Comment by egtann** [comment]
True, but it can easily match the protocol of the request with `window.location.protocol` replacing `http:`

Definitely a corner-case issue, but I have a plugin that forces HTTPS whenever possible. So originally your http link was converted to https automatically for me, breaking it.

**Comment by DaleWebb** [comment]
Is that the request on the demo page to rawgit.com?

**Comment by egtann** [comment]
Yeah

**Comment by DaleWebb** [comment]
Just changed it to // rather than http://

**Comment by egtann** [comment]
Works great! :)
