### ISSUE TITLE
iOS keyboard hides messages

### ISSUE THREAD

**Issue by egtann** [DaleWebb/abot-widget#6]
The view should scroll to the correct place when the keyboard becomes visible. Right now messages hide off the top of the screen.

Also the textbox should also change the keyboard type to include a blue "Send" button (or something like it) to let the user know that "Return" will send his/her message.

**Comment by DaleWebb** [comment]
Yeah that happens to me too.  I'm thinking that this sort of thing will be easier to handle by creating components with something like React

**Comment by egtann** [comment]
React is way too heavy to include in any JS library.

**Comment by DaleWebb** [comment]
Okay, I'll have to find a convention or pattern to manage the code in a similar way
